apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix-standalone.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "apisix-standalone.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.targetPort }}
      protocol: TCP
      name: https
    {{- if .Values.service.admin }}
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.targetPort }}
      protocol: TCP
      name: admin
    {{- end }}
  selector:
    {{- include "apisix-standalone.selectorLabels" . | nindent 4 }}