apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apisix-standalone.fullname" . }}-ca-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "apisix-standalone.labels" . | nindent 4 }}
data:
  ca-certificates.crt: |
    # CA Certificate Bundle for APISIX
    # This file contains trusted CA certificates for SSL verification
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
    ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
    b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
    MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
    b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
    ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
    9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
    IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
    VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
    93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
    jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
    A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
    U5PMCCjjmCXPI6T53iHTfIuJruydjsw2hUwsqdYXDuF8+5nqslcekdw6PewPO0k6
    nH5oFiHanOlstjXvV6CFzlplz7uY7ZZw0h3YrKrCA5sP5lckboZMp+6XAE9W9Tnt
    2U1TaV7yD3jNezLD/T6mIBaLF4c5bVj3aVg6cuIW6NZlKZxWOZy0bEh6xC5dI0Kr
    qZx8hwb6yi8/D8u0DSMWJi3MBOENc9FJcO2idaVF3GQp+Pkl1KYW7tMoZJCAh8TQ
    TXJ2YaHnFUGFTggKz8E+5mI+dubu
    -----END CERTIFICATE-----